//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

//
// This source code was auto-generated by xsd, Version=4.6.1055.0.
//


/// <remarks/>

namespace eaw.build.data.config.v2
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/eaw-build")]
    [System.Xml.Serialization.XmlRootAttribute("ModProject", Namespace = "http://www.example.org/eaw-build",
        IsNullable = false)]
    public partial class ModProjectType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private ModInfoType modInfoField;

        private BuildSettingsType buildSettingsField;

        /// <remarks/>
        public ModInfoType ModInfo
        {
            get { return this.modInfoField; }
            set
            {
                this.modInfoField = value;
                this.RaisePropertyChanged("ModInfo");
            }
        }

        /// <remarks/>
        public BuildSettingsType BuildSettings
        {
            get { return this.buildSettingsField; }
            set
            {
                this.buildSettingsField = value;
                this.RaisePropertyChanged("BuildSettings");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/eaw-build")]
    public partial class ModInfoType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private ModNameType nameField;

        private ModDescriptionType descriptionField;

        private ModVersionType versionField;

        private string iconPathField;

        private SteamMetaDataType steamMetaDataField;

        /// <remarks/>
        public ModNameType Name
        {
            get { return this.nameField; }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }

        /// <remarks/>
        public ModDescriptionType Description
        {
            get { return this.descriptionField; }
            set
            {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }

        /// <remarks/>
        public ModVersionType Version
        {
            get { return this.versionField; }
            set
            {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }

        /// <remarks/>
        public string IconPath
        {
            get { return this.iconPathField; }
            set
            {
                this.iconPathField = value;
                this.RaisePropertyChanged("IconPath");
            }
        }

        /// <remarks/>
        public SteamMetaDataType SteamMetaData
        {
            get { return this.steamMetaDataField; }
            set
            {
                this.steamMetaDataField = value;
                this.RaisePropertyChanged("SteamMetaData");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/eaw-build")]
    public partial class ModNameType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string shortNameField;

        private string longNameField;

        /// <remarks/>
        public string ShortName
        {
            get { return this.shortNameField; }
            set
            {
                this.shortNameField = value;
                this.RaisePropertyChanged("ShortName");
            }
        }

        /// <remarks/>
        public string LongName
        {
            get { return this.longNameField; }
            set
            {
                this.longNameField = value;
                this.RaisePropertyChanged("LongName");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/eaw-build")]
    public partial class MoveDefinitionsType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private DirectoryType[] directoriesField;

        private string[] filesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Directory", IsNullable = false)]
        public DirectoryType[] Directories
        {
            get { return this.directoriesField; }
            set
            {
                this.directoriesField = value;
                this.RaisePropertyChanged("Directories");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("File", IsNullable = false)]
        public string[] Files
        {
            get { return this.filesField; }
            set
            {
                this.filesField = value;
                this.RaisePropertyChanged("Files");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/eaw-build")]
    public partial class DirectoryType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string directoryPathField;

        private string fileSearchPatternField;

        private bool recursiveField;

        private bool recursiveFieldSpecified;

        /// <remarks/>
        public string DirectoryPath
        {
            get { return this.directoryPathField; }
            set
            {
                this.directoryPathField = value;
                this.RaisePropertyChanged("DirectoryPath");
            }
        }

        /// <remarks/>
        public string FileSearchPattern
        {
            get { return this.fileSearchPatternField; }
            set
            {
                this.fileSearchPatternField = value;
                this.RaisePropertyChanged("FileSearchPattern");
            }
        }

        /// <remarks/>
        public bool Recursive
        {
            get { return this.recursiveField; }
            set
            {
                this.recursiveField = value;
                this.RaisePropertyChanged("Recursive");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecursiveSpecified
        {
            get { return this.recursiveFieldSpecified; }
            set
            {
                this.recursiveFieldSpecified = value;
                this.RaisePropertyChanged("RecursiveSpecified");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/eaw-build")]
    public partial class BundleContentType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private DirectoryType[] directoriesField;

        private string[] filesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Directory", IsNullable = false)]
        public DirectoryType[] Directories
        {
            get { return this.directoriesField; }
            set
            {
                this.directoriesField = value;
                this.RaisePropertyChanged("Directories");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("File", IsNullable = false)]
        public string[] Files
        {
            get { return this.filesField; }
            set
            {
                this.filesField = value;
                this.RaisePropertyChanged("Files");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/eaw-build")]
    public partial class BundleType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string nameField;

        private BundleContentType contentField;

        /// <remarks/>
        public string Name
        {
            get { return this.nameField; }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }

        /// <remarks/>
        public BundleContentType Content
        {
            get { return this.contentField; }
            set
            {
                this.contentField = value;
                this.RaisePropertyChanged("Content");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/eaw-build")]
    public partial class CookSettingsType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string outputDirectoryField;

        private BundleType[] bundleDefinitionsField;

        private MoveDefinitionsType moveDefinitionsField;

        /// <remarks/>
        public string OutputDirectory
        {
            get { return this.outputDirectoryField; }
            set
            {
                this.outputDirectoryField = value;
                this.RaisePropertyChanged("OutputDirectory");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Bundle", IsNullable = false)]
        public BundleType[] BundleDefinitions
        {
            get { return this.bundleDefinitionsField; }
            set
            {
                this.bundleDefinitionsField = value;
                this.RaisePropertyChanged("BundleDefinitions");
            }
        }

        /// <remarks/>
        public MoveDefinitionsType MoveDefinitions
        {
            get { return this.moveDefinitionsField; }
            set
            {
                this.moveDefinitionsField = value;
                this.RaisePropertyChanged("MoveDefinitions");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/eaw-build")]
    public partial class LocalisationSettingsType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string localisationProjectFileField;

        private LocalisationProjectVersionType localisationProjectVersionField;

        /// <remarks/>
        public string LocalisationProjectFile
        {
            get { return this.localisationProjectFileField; }
            set
            {
                this.localisationProjectFileField = value;
                this.RaisePropertyChanged("LocalisationProjectFile");
            }
        }

        /// <remarks/>
        public LocalisationProjectVersionType LocalisationProjectVersion
        {
            get { return this.localisationProjectVersionField; }
            set
            {
                this.localisationProjectVersionField = value;
                this.RaisePropertyChanged("LocalisationProjectVersion");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/eaw-build")]
    public enum LocalisationProjectVersionType
    {

        /// <remarks/>
        v1,

        /// <remarks/>
        v2,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/eaw-build")]
    public partial class BuildSettingsType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private LocalisationSettingsType localisationSettingsField;

        private CookSettingsType cookSettingsField;

        /// <remarks/>
        public LocalisationSettingsType LocalisationSettings
        {
            get { return this.localisationSettingsField; }
            set
            {
                this.localisationSettingsField = value;
                this.RaisePropertyChanged("LocalisationSettings");
            }
        }

        /// <remarks/>
        public CookSettingsType CookSettings
        {
            get { return this.cookSettingsField; }
            set
            {
                this.cookSettingsField = value;
                this.RaisePropertyChanged("CookSettings");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/eaw-build")]
    public partial class SteamMetaDataType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string publishedFileIdField;

        private SteamVisibilityType visibilityField;

        private SteamGameModeType gameModeField;

        private SteamTagType[] tagsField;

        private string contentFolderField;

        private string additionalMetaDataField;

        /// <remarks/>
        public string PublishedFileId
        {
            get { return this.publishedFileIdField; }
            set
            {
                this.publishedFileIdField = value;
                this.RaisePropertyChanged("PublishedFileId");
            }
        }

        /// <remarks/>
        public SteamVisibilityType Visibility
        {
            get { return this.visibilityField; }
            set
            {
                this.visibilityField = value;
                this.RaisePropertyChanged("Visibility");
            }
        }

        /// <remarks/>
        public SteamGameModeType GameMode
        {
            get { return this.gameModeField; }
            set
            {
                this.gameModeField = value;
                this.RaisePropertyChanged("GameMode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Tag", IsNullable = false)]
        public SteamTagType[] Tags
        {
            get { return this.tagsField; }
            set
            {
                this.tagsField = value;
                this.RaisePropertyChanged("Tags");
            }
        }

        /// <remarks/>
        public string ContentFolder
        {
            get { return this.contentFolderField; }
            set
            {
                this.contentFolderField = value;
                this.RaisePropertyChanged("ContentFolder");
            }
        }

        /// <remarks/>
        public string AdditionalMetaData
        {
            get { return this.additionalMetaDataField; }
            set
            {
                this.additionalMetaDataField = value;
                this.RaisePropertyChanged("AdditionalMetaData");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/eaw-build")]
    public enum SteamVisibilityType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/eaw-build")]
    public enum SteamGameModeType
    {

        /// <remarks/>
        EAW,

        /// <remarks/>
        FOC,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/eaw-build")]
    public enum SteamTagType
    {

        /// <remarks/>
        SinglePlayer,

        /// <remarks/>
        Multiplayer,

        /// <remarks/>
        Land,

        /// <remarks/>
        Space,

        /// <remarks/>
        Campaign,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/eaw-build")]
    public partial class ModVersionType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private int majorField;

        private int minorField;

        private int patchField;

        private int buildField;

        /// <remarks/>
        public int Major
        {
            get { return this.majorField; }
            set
            {
                this.majorField = value;
                this.RaisePropertyChanged("Major");
            }
        }

        /// <remarks/>
        public int Minor
        {
            get { return this.minorField; }
            set
            {
                this.minorField = value;
                this.RaisePropertyChanged("Minor");
            }
        }

        /// <remarks/>
        public int Patch
        {
            get { return this.patchField; }
            set
            {
                this.patchField = value;
                this.RaisePropertyChanged("Patch");
            }
        }

        /// <remarks/>
        public int Build
        {
            get { return this.buildField; }
            set
            {
                this.buildField = value;
                this.RaisePropertyChanged("Build");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/eaw-build")]
    public partial class ModDescriptionType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string summaryField;

        private string descriptionField;

        /// <remarks/>
        public string Summary
        {
            get { return this.summaryField; }
            set
            {
                this.summaryField = value;
                this.RaisePropertyChanged("Summary");
            }
        }

        /// <remarks/>
        public string Description
        {
            get { return this.descriptionField; }
            set
            {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
